### ISSUE TITLE
Private Network Example

### ISSUE THREAD

**Issue by hrsantiago** [latitudesh/examples#44]
Hello, the private network example does not work properly.

https://github.com/latitudesh/examples/blob/main/user-data/private-network/data.yaml

There are 2 problems:
1) The file /etc/netplan/50-cloud-init.yaml does not exist.
2) yq is not found, probably due to PATH not being updated after installing it/snap

It works this way:
`INTERFACE=$(cat /etc/cloud/cloud.cfg.d/50-curtin-networking.cfg | /snap/bin/yq e '.network.ethernets[] | select(has("gateway4") | not ) | path | .[-1]' -)`

**Comment by hrsantiago** [comment]
Another question related to this:

Is there a way to auto assign a new server to a private network?
![image](https://github.com/user-attachments/assets/baafe82c-b40e-48e5-a177-f4f2d3752e61)

It feels wrong to be 2 separate actions: deploy the server and then assign it to a vlan.
The server is already running when I assign it to a vlan, so this script can fail if I take too long.

The suggestion is:
Add a Vlan select in the Options part of deploy server. So it'll be assigned whenever possible.

**Comment by hrsantiago** [comment]
It was Debian 12

**Comment by ynhummel** [comment]
Hello @hrsantiago, thanks for reporting this problem!

Normally, the examples are based on one operating system, and the code might need some adjustments when used on others.

In this case, the example works well on Ubuntu, especially Ubuntu 24.04, which we offer as an [Instant deploy](https://www.latitude.sh/docs/servers/deploying-a-server#instant-deployments) option. Unfortunately, this example isn't working well on Debian 12.

**Comment by hrsantiago** [comment]
Alright, maybe this should be on the readme or as a comment on the example.

**Comment by esoubihe** [comment]
@hrsantiago thanks for the feedback, this has been merged on #45. We'd love it if you could open a PR adding support for Debian 12.
